name: 마사이 마라 공원 dockerhub

on:
  workflow_dispatch

jobs:
  dockerhub:
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: login to docker hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: docker operations
          run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/massai_mara:v1 .
            docker push ${{ secrets.DOCKER_USERNAME }}/massai_mara:v1

        - name: logout from dockerhub
          if: always()
          run: docker logout

        - name: run docker container
          run: |
            docker run -d --name maratang -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/massai_mara:v1
            sleep 20
            docker ps
            docker logs maratang

        - name: run automated test #1
          run: |
            curl http://localhost:8080 || exit 1

        - name: run automated test #2
          run: |
            curl http://localhost:8080/images || exit 1

        - name: run automated test #3
          run: |
            curl http://localhost:8080/animal || exit 1